{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "verisure-exporter.fullname" . }}
  labels:
    {{- include "verisure-exporter.labels" . | nindent 4 }}
spec:
  description: "Network policy for verisure-exporter"
  endpointSelector:
    matchLabels:
      {{- include "verisure-exporter.selectorLabels" . | nindent 6 }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: prometheus
    toPorts:
    - ports:
      - port: {{ .Values.exporter.port | quote }}
        protocol: TCP
  egress:
  - toFQDNs:
    - matchName: "m-api01.verisure.com"
    - matchName: "automation.verisure.com"
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      rules:
        dns:
        - matchPattern: "*.verisure.com"
{{- end }}
